"Set compatibility to vim only
set nocompatible

" Automatically wrap text that extends beyond the screen length
set wrap

" Encoding
set encoding=utf-8

"Show line numbers
set number

"Turn on syntax colors
syntax on

"Status bar
set laststatus=2

" Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

" Indentation and auto-indent setting
set autoindent
set tabstop=4
set shiftwidth=4

" Hilight and line number color
hi LineNr ctermfg=DarkGrey ctermbg=Black
set cursorline
" hi CursorLine ctermbg=DarkGrey
hi clear CursorLine
hi CursorLineNr cterm=bold ctermfg=LightCyan ctermbg=NONE
